json.id product.id
json.name product.name
json.price product.price
json.image_url product.image_url
json.description product.description
json.is_discounted? product.is_discounted?
json.sales_tax product.tax
json.sales_total product.total
json.supplier product.supplier
json.image product.image
